import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { geoConfig } from '../config/geo.js';
import { flagFromCode, fuzzySearch, normalizeGeoName } from '../utils/geoNormalize.js';
import { logger } from '../utils/logger.js';

/**
 * Reference data for countries and cities (ТЗ §7, §8).
 *
 * The dataset is generated by scripts/build-geo-data.ts and shipped with the
 * bot, so lookups need no network and no database table. Country data is small
 * enough to load eagerly; city files are loaded per country on first use and
 * cached, because a city search is always scoped to the country the user has
 * already picked.
 */

export interface GeoCountry {
  code: string;
  name: string;
  nameEn: string;
  population: number;
  /** How many cities are known for this country. */
  cities: number;
  flag: string;
}

export interface GeoCity {
  id: number;
  name: string;
  population: number;
  countryCode: string;
}

export interface GeoSearchResult<T> {
  /** Set when exactly one entry matches the query outright. */
  exact: T | null;
  /** Ranked alternatives to offer as buttons. */
  suggestions: T[];
}

interface RawCountry {
  code: string;
  name: string;
  nameEn: string;
  population: number;
  cities: number;
  keys: string[];
}

interface RawCity {
  id: number;
  name: string;
  population: number;
  keys: string[];
}

const dataDir = new URL('../data/', import.meta.url);

function readJson<T>(relativePath: string): T {
  const path = fileURLToPath(new URL(relativePath, dataDir));
  return JSON.parse(readFileSync(path, 'utf8')) as T;
}

let countryIndex: Map<string, RawCountry> | null = null;

function countries(): Map<string, RawCountry> {
  if (!countryIndex) {
    const { countries: rows } = readJson<{ countries: RawCountry[] }>('countries.json');
    countryIndex = new Map(rows.map((row) => [row.code, row]));
    logger.debug({ countries: countryIndex.size }, 'Country reference data loaded');
  }
  return countryIndex;
}

const cityCache = new Map<string, RawCity[]>();

function cities(countryCode: string): RawCity[] {
  const cached = cityCache.get(countryCode);
  if (cached) return cached;

  let rows: RawCity[] = [];
  try {
    rows = readJson<{ cities: RawCity[] }>(`cities/${countryCode}.json`).cities;
  } catch (error) {
    logger.warn({ err: error, countryCode }, 'No city reference data for country');
  }

  // Bound the memory a long-running process can accumulate.
  if (cityCache.size >= geoConfig.cityCacheCountries) {
    const oldest = cityCache.keys().next();
    if (!oldest.done) cityCache.delete(oldest.value);
  }
  cityCache.set(countryCode, rows);
  return rows;
}

function toCountry(raw: RawCountry): GeoCountry {
  return {
    code: raw.code,
    name: raw.name,
    nameEn: raw.nameEn,
    population: raw.population,
    cities: raw.cities,
    flag: flagFromCode(raw.code),
  };
}

function toCity(raw: RawCity, countryCode: string): GeoCity {
  return {
    id: raw.id,
    name: raw.name,
    population: raw.population,
    countryCode,
  };
}

export const geoService = {
  /** Countries offered as one-tap buttons before the user starts typing. */
  listPopularCountries(): GeoCountry[] {
    return geoConfig.popularCountries
      .map((code) => countries().get(code))
      .filter((raw): raw is RawCountry => Boolean(raw))
      .map(toCountry);
  },

  getCountry(code: string | null | undefined): GeoCountry | null {
    if (!code) return null;
    const raw = countries().get(code.toUpperCase());
    return raw ? toCountry(raw) : null;
  },

  /**
   * Resolves free-form country input. "Україна", "украина" and "Ukraina" all
   * resolve exactly; "Укрна" comes back as a suggestion; gibberish comes back
   * with nothing at all so the bot can say the country does not exist.
   */
  searchCountries(query: string, limit = geoConfig.suggestionLimit): GeoSearchResult<GeoCountry> {
    const matches = fuzzySearch(
      query,
      [...countries().values()].map((raw) => ({
        item: raw,
        keys: raw.keys,
        weight: raw.population,
      })),
      { limit: limit + 4 },
    );

    const exactMatches = matches.filter((match) => match.kind === 'exact');
    // Two countries never share a normalised name, so one exact hit is decisive.
    const exact = exactMatches.length === 1 ? toCountry(exactMatches[0]!.item) : null;

    return {
      exact,
      suggestions: matches.slice(0, limit).map((match) => toCountry(match.item)),
    };
  },

  listTopCities(countryCode: string, limit = geoConfig.topCityButtons): GeoCity[] {
    // The generated files are already sorted by population, biggest first.
    return cities(countryCode)
      .slice(0, limit)
      .map((raw) => toCity(raw, countryCode));
  },

  getCity(countryCode: string, cityId: number): GeoCity | null {
    const raw = cities(countryCode).find((city) => city.id === cityId);
    return raw ? toCity(raw, countryCode) : null;
  },

  /** Same contract as searchCountries, scoped to one country. */
  searchCities(
    countryCode: string,
    query: string,
    limit = geoConfig.suggestionLimit,
  ): GeoSearchResult<GeoCity> {
    const rows = cities(countryCode);
    if (rows.length === 0) return { exact: null, suggestions: [] };

    const matches = fuzzySearch(
      query,
      rows.map((raw) => ({ item: raw, keys: raw.keys, weight: raw.population })),
      { limit: limit + 6 },
    );

    const exactMatches = matches.filter((match) => match.kind === 'exact');
    // Same-named towns are common, so an exact hit only wins when it is alone
    // or clearly the biggest one.
    let exact: GeoCity | null = null;
    if (exactMatches.length === 1) {
      exact = toCity(exactMatches[0]!.item, countryCode);
    } else if (exactMatches.length > 1) {
      const [first, second] = exactMatches;
      if (first && second && first.item.population >= second.item.population * 10) {
        exact = toCity(first.item, countryCode);
      }
    }

    return {
      exact,
      suggestions: matches.slice(0, limit).map((match) => toCity(match.item, countryCode)),
    };
  },

  /** True when two stored city names refer to the same place. */
  isSameCityName(a: string | null | undefined, b: string | null | undefined): boolean {
    if (!a || !b) return false;
    return normalizeGeoName(a) === normalizeGeoName(b);
  },

  /** Diagnostics for /admin and the startup log. */
  stats(): { countries: number; citiesLoaded: number } {
    return {
      countries: countries().size,
      citiesLoaded: [...cityCache.values()].reduce((sum, rows) => sum + rows.length, 0),
    };
  },
};
