/**
 * Country and city picker behaviour (ТЗ §7, §8).
 *
 * The reference data itself lives in src/data (generated by
 * scripts/build-geo-data.ts); only presentation choices belong here.
 */
export const geoConfig = {
  /**
   * Countries shown as one-tap buttons. Everything else is reachable by typing
   * the name — the full ISO list is searchable.
   */
  popularCountries: ['MD', 'UA', 'RO', 'PL', 'DE', 'RU', 'IL', 'ES', 'IT', 'US'],
  /** Buttons per row in the country picker. */
  countriesPerRow: 2,
  /** How many "did you mean" options to offer. */
  suggestionLimit: 6,
  /** Biggest cities offered as buttons on the city step. */
  topCityButtons: 8,
  /** Country city-lists kept in memory at once (each is a few hundred KB). */
  cityCacheCountries: 8,
};
